name: Metrics

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - master

  schedule:
    - cron: "0 */12 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate 3D contribution calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: yousefdawood7

          # Output file
          filename: github-metrics.svg

          # Hide everything except the 3D calendar
          base: ""

          # 3D contribution graph
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
